### ISSUE TITLE
Week 1 Completed App Review

### ISSUE THREAD

**Issue by audip** [audip/MovieFlicks#4]
My app is complete, please review. /cc @codepathreview

**Comment by codepathreview** [comment]
:+1: Nice work! The point of this homework was to get a chance to implement a TableView (one of the most common views in iOS) and to work with real data over the network (in this case from the Movies Database API).

A key part of these projects is that you add additional features and tweak the UI / UX because that will provide the most learning opportunities. We encourage you to complete the projects early each week with the required stories and then spend time adding your own UI elements and experimenting with optional extensions that will improve the user experience.

### Some small comments:
- Please be sure to follow the Swift code styling conventions for the homework .
  - Here is the useful guide: [Ray Wenderlich Swift Style Guide](https://github.com/raywenderlich/swift-style-guide)
- Good job using `if let` to unwrap variables :+1: 
- Please put the ` `and`{` at the right positions. For example this code:

``` Swift
        UIView.animateWithDuration(0.5, delay: 0.2, options: .CurveEaseOut, animations:
            {
                cell.posterView.alpha = 1.0
                cell.titleLabel.alpha = 1.0
                cell.overviewLabel.alpha = 1.0
                cell.ratingLabel.alpha = 1.0
                cell.yearLabel.alpha = 1.0
            },
            completion:
            {
                (finished:Bool) in
            }
        )
```

   Please put `{` at the end of the line.
- You can initialize `movies` when declare like this `var movies = [NSDictionary]()` so you can use it anywhere without unwrapping. By this way, the function `numberOfRowsInSection` will be simpler, just use `return movies.count`.
- When create new project, you can uncheck `Include Unit Test` and `Include UI Test` if you don't write test for your app.

<img width="145" alt="screen shot 2016-01-31 at 8 16 37 pm" src="https://cloud.githubusercontent.com/assets/7917093/12702296/9567e674-c857-11e5-9904-ac36e27b69b8.png">
- Please remove commented code in your project.
- Well done with customizing UI :star2: 

We have a detailed [Project 1 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_1_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.
